sudo: required
services:
  - docker

before_install:
  - docker build -t usermikez/docker-reacts -f Dockerfile.dev .

script:
  - docker run -e CI=true usermikez/docker-reacts npm run test -- --coverage